In [11]:
import pandas as pd
import numpy as np

import csv
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit

In [12]:
# Model-specific imports:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification

In [13]:
inputData = pd.read_csv(r'/Users/whitney/Downloads/CTG1.csv').sample(frac = 1)

inputData.head()

LB  AC  FM  UC  ASTV  MSTV  ALTV  MLTV  DL  DS  DP  NSP
1612  135   2  46   4    65   2.0     0   5.2   1   0   0    1
80    145   0   1   1    34   1.7     0  25.9   0   0   0    1
1689  137  17   0   8    56   2.4     0   0.4   5   0   0    1
1039  125   0   0   3    38   0.8    18   6.7   0   0   0    1
486   127  10   4   0    35   1.2     0   5.1   1   0   0    1

In [14]:
# select the input brain volume vector (X) and the output age vector (y)
X = inputData.drop(columns=['NSP'])
y = inputData['NSP']

# split the X and y vectors into training and testing dataset
# we're using 80% for training and 20% for testing, but this can change
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [15]:
ada = AdaBoostClassifier(n_estimators=100, random_state=0)

ada.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [21]:
# check the model's performance on unseen, test data
ada_predictions = ada.predict(X_test)

# compare the predictions to the known values (y_test)
print('accuracy', metrics.accuracy_score(y_test, ada_predictions, normalize=True, sample_weight=None))
print('precision:', metrics.precision_score(y_test, ada_predictions, average='macro'))
print('recall:', metrics.recall_score(y_test, ada_predictions, average='macro'))
print(metrics.confusion_matrix(y_test, ada_predictions))

accuracy 0.7910798122065728
precision: 0.7574024554341019
recall: 0.769689870593485
[[264  66   2]
 [  6  48   0]
 [ 11   4  25]]
