In [11]:
import pandas as pd
import numpy as np

import csv
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit

In [12]:
# Model-specific imports:
from sklearn.naive_bayes import BernoulliNB

In [13]:
inputData = pd.read_csv(r'/Users/whitney/Downloads/CTG1.csv').sample(frac = 1)

inputData.head()

LB  AC  FM  UC  ASTV  MSTV  ALTV  MLTV  DL  DS  DP  NSP
165   134   3   9   1    56   3.2     0  41.8   1   0   0    1
1184  120   0   0   9    51   0.7     4  11.4   0   0   0    1
1813  143   0   0   8    66   0.4     4  13.6   0   0   0    1
885   136   0   0   1    44   0.7    47   5.3   0   0   0    1
1121  122   0   0   1    25   1.3     4   9.5   0   0   0    1

In [14]:
# select the input brain volume vector (X) and the output age vector (y)
X = inputData.drop(columns=['NSP'])
y = inputData['NSP']

# split the X and y vectors into training and testing dataset
# we're using 80% for training and 20% for testing, but this can change
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [15]:
clf = BernoulliNB()

clf.fit (X_train, y_train)

BernoulliNB()

In [21]:
# check the model's performance on unseen, test data
clf_predictions = clf.predict(X_test)

# compare the predictions to the known values (y_test)
print('accuracy', metrics.accuracy_score(y_test, clf_predictions, normalize=True, sample_weight=None))
print('precision:', metrics.precision_score(y_test, clf_predictions, average='macro'))
print('recall:', metrics.recall_score(y_test, clf_predictions, average='macro'))
print(metrics.confusion_matrix(y_test, clf_predictions))

accuracy 0.8004694835680751
precision: 0.6770880783908814
recall: 0.6981374662963323
[[279  44   8]
 [ 18  45   1]
 [  1  13  17]]
