In [47]:
import pandas as pd
import numpy as np

import csv
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit

In [48]:
# Model-specific imports:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [49]:
inputData = pd.read_csv(r'/Users/whitney/Downloads/CTG1.csv').sample(frac = 1)

inputData.head()

LB  AC  FM  UC  ASTV  MSTV  ALTV  MLTV  DL  DS  DP  NSP
465   144   0   2   1    78   0.6    23  11.0   1   0   0    2
343   139   0   6   0    75   0.4    47   9.2   0   0   0    2
1455  148   0   0   3    41   1.0     5  13.4   0   0   0    2
1017  139   1   0   1    38   1.0     0  11.7   0   0   0    1
2097  133   0   0   4    75   0.6    20   4.7   0   0   0    1

In [50]:
# select the input brain volume vector (X) and the output age vector (y)
X = inputData.drop(columns=['NSP'])
y = inputData['NSP']

# split the X and y vectors into training and testing dataset
# we're using 80% for training and 20% for testing, but this can change
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [51]:
sgd = make_pipeline(StandardScaler(), SGDClassifier(max_iter=1000, tol=1e-3))

sgd.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

In [56]:
# check the model's performance on unseen, test data
sgd_predictions = sgd.predict(X_test)

# compare the predictions to the known values (y_test)
print('accuracy', metrics.accuracy_score(y_test, sgd_predictions, normalize=True, sample_weight=None))
print('precision:', metrics.precision_score(y_test, sgd_predictions, average='macro'))
print('recall:', metrics.recall_score(y_test, sgd_predictions, average='macro'))
print(metrics.confusion_matrix(y_test, sgd_predictions))

accuracy 0.8450704225352113
precision: 0.7137626262626263
recall: 0.73996239183012
[[301  14   7]
 [ 27  31  13]
 [  2   3  28]]
